spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsSystem
    username: root
    password: zww
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create